### ISSUE TITLE
[Q] What does mean their names?

### ISSUE THREAD

**Issue by RyogaK** [capnkirok/InventoryPetsLocalization#15]
@capnkirok 

Hi, I want to know to translate to Japanese again.
So could you tell me what their names mean and the origin of name.

### The list of names that I don't understand.
- Pingot
- Mickerson
- Quantum Crystal Monster (Which does quantum mean, `the quantum` or` a few`?)

**Comment by capnkirok** [comment]
Hey @RyogaK ! An update to the lang file sounds great.

- Pingot refers to the fact it uses sonar ping to locate nearby ores. So, it's kind of funny. Ping + Ingot = Pingot
- Mickerson is just someone's name. Kind of an inside joke in this house.
- Quantum refers to "the minimum amount of any physical entity involved in an interaction" You can refer to https://en.wikipedia.org/wiki/Quantum

**Comment by RyogaK** [comment]
Thanks for your quick response!
I,ll try to submit PR tonight (at night of Japan)
